### ISSUE TITLE
Cluster bootstrapping docs

### ISSUE THREAD

**Issue by rimusz** [pharmer/pharmer#223]
Docs how to bootstrap clusters on different cloud providers would be very helpful.

**Comment by tamalsaha** [comment]
Yeah. Docs are coming.

**Comment by tamalsaha** [comment]
@rimusz , here are the initial docs for DO: https://github.com/appscode/pharmer/blob/master/cloud/providers/digitalocean/README.md

More docs are coming.

**Comment by tamalsaha** [comment]
Docs are added.
