### ISSUE TITLE
AWS: unused volume attached to master

### ISSUE THREAD

**Issue by lbogdan** [pharmer/pharmer#385]
When creating a cluster on AWS, a persistent volume is attached to the master in [cloud.go:985](https://github.com/pharmer/pharmer/blob/master/cloud/providers/aws/cloud.go#L985). From what I can see, it's not mounted:
```
master:~$ mount | grep xvd
/dev/xvda1 on / type ext4 (rw,relatime,discard,data=ordered)
/dev/xvda1 on /var/lib/docker/aufs type ext4 (rw,relatime,discard,data=ordered)
master:~$ _
```
What is it used for?

**Comment by tamalsaha** [comment]
The master disk is used to store etcd data. Fixed by #391
