### ISSUE TITLE
Add cluster-admin token to kubeconfig

### ISSUE THREAD

**Issue by ianwalter** [pharmer/pharmer#392]
Apologies if this is outside of scope or a duplicate. I'm still in the process of understanding how Kubernetes works.

I created a cluster using pharmer and deployed the Kubernetes Dashboard but apparently it won't let me use the .kube/config that pharmer generated because it needs the user to authenticate using an auth token instead of a certificate. I'm not sure how to do this, but is this token something that pharmer can add automatically to .kube/config in addition to the certificate so that this works a bit more seamlessly?

**Comment by sanjid133** [comment]
@ianwalter Can you please add the error logs here?

**Comment by ianwalter** [comment]
Error: Not enough data to create auth info structure.

But I'm going to close this since it doesn't really have to do with pharmer. Although, I think it would be cool to add an option to automatically set up guard when pharmer creates the cluster and then you could use that to "sign in" to the Kubernetes Dashboard.
