### ISSUE TITLE
pharmer ssh fails with "failed to detect external Ip for node..."

### ISSUE THREAD

**Issue by jfrederickson** [pharmer/pharmer#429]
I recently attempted to stand up a k8s cluster on Linode using Pharmer. The cluster appears to have been brought up successfully (`kubectl` is able to communicate with the cluster after `pharmer use <cluster>`), but I get this error when attempting to log into a node with `pharmer ssh`:

```
[jon@terralibre ~]$ pharmer ssh node l1-045-079-167-190 -k l1
I0519 16:23:58.620292    9978 logs.go:19] FLAG: --alsologtostderr="false"
I0519 16:23:58.620381    9978 logs.go:19] FLAG: --analytics="true"
I0519 16:23:58.620496    9978 logs.go:19] FLAG: --cluster="l1"
I0519 16:23:58.620517    9978 logs.go:19] FLAG: --config-file=""
I0519 16:23:58.620582    9978 logs.go:19] FLAG: --env="prod"
I0519 16:23:58.620610    9978 logs.go:19] FLAG: --help="false"
I0519 16:23:58.620676    9978 logs.go:19] FLAG: --log_backtrace_at=":0"
I0519 16:23:58.620741    9978 logs.go:19] FLAG: --log_dir=""
I0519 16:23:58.620759    9978 logs.go:19] FLAG: --logtostderr="true"
I0519 16:23:58.620778    9978 logs.go:19] FLAG: --stderrthreshold="0"
I0519 16:23:58.620807    9978 logs.go:19] FLAG: --v="0"
I0519 16:23:58.620826    9978 logs.go:19] FLAG: --vmodule=""
F0519 16:23:59.287650    9978 ssh_node.go:43] [failed to detect external Ip for node l1-045-079-167-190 of cluster l1]
```

**Comment by tamalsaha** [comment]
Hi, if you do `kubectl get nodes <node-name> -o yaml`, does that show the public/external IP of that node?

**Comment by jfrederickson** [comment]
It doesn't appear to, no. As it doesn't appear to contain any sensitive info (and this is a test cluster anyway), here's the complete output: https://gist.github.com/jfrederickson/1e7b70675819efc258457bdad70bee18

**Comment by tamalsaha** [comment]
So, that is the problem. We are going to look into that.

**Comment by sanjid133** [comment]
@jfrederickson we have updated cloud-controller-manager version ( https://github.com/pharmer/addons/pull/5 ). This should fixed that error.
