### ISSUE TITLE
ssh connection refused 

### ISSUE THREAD

**Issue by thisroot** [pharmer/pharmer#462]
Hi, i attempt to install kubernates using pharmer on a scaleway. But get an errors. Refused ssh connection
 
```bash
 dial tcp 212.47.254.110:22: connect: connection refused', retrying
 'ssh: must specify HostKeyCallback', retrying
```
- config:
```
pharmer create cluster s4 \
 	--provider=scaleway \
 	--zone=par1 \
 	--nodes=VC1S=1 \
 	--credential-uid=scaleway \
 	--kubernetes-version=v1.11.0
```

**Comment by sanjid133** [comment]
@thisroot https://github.com/pharmer/pharmer/releases/tag/0.1.1 will fix this issue. Can you please try this?

**Comment by thisroot** [comment]
> @thisroot https://github.com/pharmer/pharmer/releases/tag/0.1.1 will fix this issue. Can you please try this?

Sorry i can't read you message at time
